Repository 19-Toy-Project/Word_Wise, pull requests merged in 2025-02, with the labels that each got.

#11 [MERGE] 카카오 소셜 로그인, Spring Security 구현
  build.gradle
  src/main/java/com/wordwise/common/apipayload/status/ErrorStatus.java
  src/main/java/com/wordwise/common/config/JwtAuthenticationToken.java
  src/main/java/com/wordwise/common/config/JwtSecurityFilter.java
  src/main/java/com/wordwise/common/config/RestTemplateConfig.java
  src/main/java/com/wordwise/common/config/WebSecurityConfig.java
  src/main/java/com/wordwise/common/enums/LoginType.java
  src/main/java/com/wordwise/common/enums/UserRole.java
  src/main/java/com/wordwise/common/enums/UserStatus.java
  src/main/java/com/wordwise/common/enums/UserTier.java
  src/main/java/com/wordwise/common/enums/WordType.java
  src/main/java/com/wordwise/common/enums/test.java
  src/main/java/com/wordwise/common/utils/JwtUtil.java
  src/main/java/com/wordwise/common/utils/WordTypeConverter.java
  src/main/java/com/wordwise/domain/auth/AuthUser.java
  src/main/java/com/wordwise/domain/auth/controller/AuthController.java
  src/main/java/com/wordwise/domain/auth/dto/KakaoUserInfoDto.java
  src/main/java/com/wordwise/domain/auth/request/KakaoUserDeleteRequest.java
  src/main/java/com/wordwise/domain/auth/request/LoginRequest.java
  src/main/java/com/wordwise/domain/auth/service/KakaoService.java
  src/main/java/com/wordwise/domain/test.java
  src/main/java/com/wordwise/domain/user/controller/UserController.java
  src/main/java/com/wordwise/domain/user/entity/User.java
  src/main/java/com/wordwise/domain/user/repository/UserRepository.java
  src/main/java/com/wordwise/domain/user/response/UserProfileResponse.java
  src/main/java/com/wordwise/domain/user/service/UserService.java
  src/main/resources/application.yaml
Labels: ✨Feature

#13 [MERGE] 영어단어, 문장 조회 및 저장 기능 구현
  build.gradle
  src/main/java/com/wordwise/WordwiseApplication.java
  src/main/java/com/wordwise/common/apipayload/status/ErrorStatus.java
  src/main/java/com/wordwise/domain/sentence/controller/SentenceController.java
  src/main/java/com/wordwise/domain/sentence/entity/Score.java
  src/main/java/com/wordwise/domain/sentence/entity/Sentence.java
  src/main/java/com/wordwise/domain/sentence/entity/Wish.java
  src/main/java/com/wordwise/domain/sentence/repository/SentenceRepository.java
  src/main/java/com/wordwise/domain/sentence/response/PapagoApiRequest.java
  src/main/java/com/wordwise/domain/sentence/response/PapagoApiResponse.java
  src/main/java/com/wordwise/domain/sentence/response/SaveSentenceResponse.java
  src/main/java/com/wordwise/domain/sentence/response/SaveSentenceScoreResponse.java
  src/main/java/com/wordwise/domain/sentence/response/WordsApiResponse.java
  src/main/java/com/wordwise/domain/sentence/service/PapagoApiClient.java
  src/main/java/com/wordwise/domain/sentence/service/SentenceService.java
  src/main/java/com/wordwise/domain/sentence/service/WordsApiClient.java
  src/main/java/com/wordwise/domain/user/entity/User.java
  src/main/java/com/wordwise/domain/word/controller/WordController.java
  src/main/java/com/wordwise/domain/word/entity/Word.java
  src/main/java/com/wordwise/domain/word/entity/WordKr.java
  src/main/java/com/wordwise/domain/word/repository/WordKrRepository.java
  src/main/java/com/wordwise/domain/word/repository/WordRepository.java
  src/main/java/com/wordwise/domain/word/response/GetWordDetailResponse.java
  src/main/java/com/wordwise/domain/word/response/GetWordListResponse.java
  src/main/java/com/wordwise/domain/word/response/SentenceResponse.java
  src/main/java/com/wordwise/domain/word/response/WordKrResponse.java
  src/main/java/com/wordwise/domain/word/service/WordService.java
  src/main/resources/application.yaml
Labels: ✨Feature

#15 [MERGE] 카카오 로그인 Backend test용 & Front 응답 api 개발
  src/main/java/com/wordwise/common/apipayload/ApiResponse.java
  src/main/java/com/wordwise/common/apipayload/dto/ReasonDto.java
  src/main/java/com/wordwise/common/apipayload/status/ErrorStatus.java
  src/main/java/com/wordwise/common/apipayload/status/SuccessStatus.java
  src/main/java/com/wordwise/common/config/WebSecurityConfig.java
  src/main/java/com/wordwise/domain/auth/controller/AuthController.java
  src/main/java/com/wordwise/domain/auth/request/LoginRequest.java
  src/main/java/com/wordwise/domain/auth/service/KakaoService.java
  src/main/resources/application.yaml
Labels: ✨Feature, 📬API

#16 [MERGE] CORS Error & 로그인 Front 연동
  src/main/java/com/wordwise/common/config/WebSecurityConfig.java
  src/main/java/com/wordwise/domain/auth/controller/AuthController.java
  src/main/java/com/wordwise/domain/auth/request/LoginRequest.java
Labels: ✨Feature, 🐞BugFix, 📬API

#20 [MERGE] CORS Error 해결
  src/main/java/com/wordwise/common/config/CorsConfig.java
  src/main/java/com/wordwise/common/config/WebSecurityConfig.java
  src/main/java/com/wordwise/domain/auth/controller/AuthController.java
Labels: ✨Feature, 🐞BugFix, 💻CrossBrowsing, 📬API

#24 [FIX] 영어단어 리스트 및 상세 Response 수정 및 찜 기능 구현
  src/main/java/com/wordwise/common/apipayload/status/ErrorStatus.java
  src/main/java/com/wordwise/domain/sentence/controller/SentenceController.java
  src/main/java/com/wordwise/domain/sentence/entity/Score.java
  src/main/java/com/wordwise/domain/sentence/entity/Sentence.java
  src/main/java/com/wordwise/domain/sentence/entity/Wish.java
  src/main/java/com/wordwise/domain/sentence/repository/WishRepository.java
  src/main/java/com/wordwise/domain/sentence/request/EtriApiRequest.java
  src/main/java/com/wordwise/domain/sentence/response/EtriApiResponse.java
  src/main/java/com/wordwise/domain/sentence/response/SaveSentenceScoreResponse.java
  src/main/java/com/wordwise/domain/sentence/service/EtriApiClient.java
  src/main/java/com/wordwise/domain/sentence/service/SentenceService.java
  src/main/java/com/wordwise/domain/word/controller/WordController.java
  src/main/java/com/wordwise/domain/word/entity/Word.java
  src/main/java/com/wordwise/domain/word/response/GetWordDetailResponse.java
  src/main/java/com/wordwise/domain/word/response/GetWordListResponse.java
  src/main/java/com/wordwise/domain/word/response/SentenceResponse.java
  src/main/java/com/wordwise/domain/word/response/WordKrResponse.java
  src/main/java/com/wordwise/domain/word/service/WordService.java
Labels: 🛠Modify

#26 [MERGE] 마이페이지 사용자 학습 평균 점수 조회
  src/main/java/com/wordwise/common/apipayload/status/ErrorStatus.java
  src/main/java/com/wordwise/common/enums/WordType.java
  src/main/java/com/wordwise/domain/mypage/controller/MyPageController.java
  src/main/java/com/wordwise/domain/mypage/dto/UserAverageScoreDto.java
  src/main/java/com/wordwise/domain/mypage/response/UserAverageScoreResponse.java
  src/main/java/com/wordwise/domain/mypage/service/MyPageService.java
  src/main/java/com/wordwise/domain/sentence/repository/ScoreRepository.java
Labels: ✨Feature, 🔨Refactor, 📬API, 🗂Database

#27 [FIX] 문장 찜 state 값 String으로 변경 및 파일 유효성 검사
  src/main/java/com/wordwise/common/utils/FileUtil.java
  src/main/java/com/wordwise/domain/sentence/controller/SentenceController.java
  src/main/java/com/wordwise/domain/sentence/service/SentenceService.java
Labels: 🛠Modify

#28 [MERGE] 사용자가 찜한 문장 조회
  src/main/java/com/wordwise/common/apipayload/status/ErrorStatus.java
  src/main/java/com/wordwise/domain/mypage/controller/MyPageController.java
  src/main/java/com/wordwise/domain/mypage/dto/UserWishSentenceDto.java
  src/main/java/com/wordwise/domain/mypage/response/UserWishSentenceListResponse.java
  src/main/java/com/wordwise/domain/mypage/service/MyPageService.java
  src/main/java/com/wordwise/domain/sentence/entity/Wish.java
  src/main/java/com/wordwise/domain/sentence/repository/WishRepository.java
Labels: ✨Feature, 📬API, 🗂Database

#29 [Feat] 녹음 주파수 변환 기능 추가
  .gitattributes
  build.gradle
  src/main/java/com/wordwise/common/utils/FileUtil.java
  src/main/java/com/wordwise/domain/sentence/service/SentenceService.java
Labels: 🛠Modify

#33 [MERGE] RefreshToken 추가
  build.gradle
  src/main/java/com/wordwise/common/apipayload/status/ErrorStatus.java
  src/main/java/com/wordwise/common/config/RedisConfig.java
  src/main/java/com/wordwise/common/utils/JwtUtil.java
  src/main/java/com/wordwise/domain/auth/controller/AuthController.java
  src/main/java/com/wordwise/domain/auth/entity/RefreshToken.java
  src/main/java/com/wordwise/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/wordwise/domain/auth/response/LoginResponse.java
  src/main/java/com/wordwise/domain/auth/service/AuthService.java
  src/main/java/com/wordwise/domain/auth/service/KakaoService.java
  src/main/java/com/wordwise/domain/mypage/service/MyPageService.java
  src/main/resources/application.yaml
Labels: ✨Feature, 💻CrossBrowsing, 📬API, 🗂Database

#34 [MERGE] WebSecurityConfig 변경 API URI 적용
  src/main/java/com/wordwise/common/config/WebSecurityConfig.java
Labels: 🐞BugFix

#35 [MERGE] JWT Security Filter "/api/v1/auth/token" 요청 정상 작동 처리 #31
  src/main/java/com/wordwise/common/config/JwtSecurityFilter.java
Labels: ✨Feature, 🐞BugFix, 🔨Refactor, 📬API

#36 [MERGE] RefreshToken으로 AccessToken 재발급 HOTFIX
  src/main/java/com/wordwise/common/apipayload/status/ErrorStatus.java
  src/main/java/com/wordwise/common/config/CorsConfig.java
  src/main/java/com/wordwise/common/config/JwtSecurityFilter.java
  src/main/java/com/wordwise/common/config/WebSecurityConfig.java
  src/main/java/com/wordwise/common/utils/JwtUtil.java
  src/main/java/com/wordwise/domain/auth/controller/AuthController.java
  src/main/java/com/wordwise/domain/auth/service/AuthService.java
  src/main/resources/application.yaml
Labels: ✨Feature, 🐞BugFix, 📬API

#41 [MERGE] 사용자가 학습한 날짜 조회
  src/main/java/com/wordwise/common/apipayload/status/ErrorStatus.java
  src/main/java/com/wordwise/common/utils/JwtUtil.java
  src/main/java/com/wordwise/domain/mypage/controller/MyPageController.java
  src/main/java/com/wordwise/domain/mypage/service/MyPageService.java
  src/main/java/com/wordwise/domain/score/entity/SentenceScore.java
  src/main/java/com/wordwise/domain/score/repository/SentenceScoreRepository.java
  src/main/java/com/wordwise/domain/score/service/DateTimeService.java
  src/main/java/com/wordwise/domain/score/service/SentenceScoreService.java
  src/main/java/com/wordwise/domain/sentence/entity/TotalScore.java
  src/main/java/com/wordwise/domain/sentence/repository/ScoreRepository.java
  src/main/java/com/wordwise/domain/sentence/service/SentenceService.java
  src/main/java/com/wordwise/domain/user/entity/User.java
Labels: ✨Feature, 🔨Refactor, 📬API, 🗂Database

#42 [MERGE] 사용자가 학습한 문장 총 개수 조회 기능
  src/main/java/com/wordwise/domain/mypage/controller/MyPageController.java
  src/main/java/com/wordwise/domain/mypage/response/UserLearnedSentenceCountResponse.java
  src/main/java/com/wordwise/domain/score/repository/SentenceScoreRepository.java
  src/main/java/com/wordwise/domain/score/service/SentenceScoreService.java
Labels: ✨Feature, 📬API, 🗂Database
